version: "2"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rails_docker_database
  backend:
    build: .
    command: rails s --b 0.0.0.0 -p 3050
    ports:
      - "3050:3050"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
  frontend:
    build: ./client
    command: npm start
    ports:
      - "8080:80"
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: development
